//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgpe.Du.Domain.Entities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cgpe.Du.Domain.Entities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El código del colegio tiene un formato incorrecto. Debe estar compuesto por una P seguida de cinco dígitos..
        /// </summary>
        internal static string AssociationCodeInvalidValidation {
            get {
                return ResourceManager.GetString("AssociationCodeInvalidValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El código del colegio es obligatorio..
        /// </summary>
        internal static string AssociationCodeRequiredValidation {
            get {
                return ResourceManager.GetString("AssociationCodeRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El colegio de la colegiación es obligatorio..
        /// </summary>
        internal static string AssociationProcuratorAssociationRequiredValidation {
            get {
                return ResourceManager.GetString("AssociationProcuratorAssociationRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;Colegio&quot; es obligatorio..
        /// </summary>
        internal static string AssociationRequiredValidation {
            get {
                return ResourceManager.GetString("AssociationRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El procurador tiene que tener al menos una colegiación..
        /// </summary>
        internal static string AssociationsProcuratorsRequiredValidation {
            get {
                return ResourceManager.GetString("AssociationsProcuratorsRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El lugar de nacimiento es obligatorio..
        /// </summary>
        internal static string BirthCityRequiredValidation {
            get {
                return ResourceManager.GetString("BirthCityRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El nombre de la ciudad natal es demasiado largo. Su longitud no deber superar los {0} caracteres..
        /// </summary>
        internal static string BirthCityTooLongValidation {
            get {
                return ResourceManager.GetString("BirthCityTooLongValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: La fecha de nacimiento es obligatoria..
        /// </summary>
        internal static string BirthDateRequiredValidation {
            get {
                return ResourceManager.GetString("BirthDateRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;Centralita&quot; no es valido..
        /// </summary>
        internal static string CentralitaInvalidValidation {
            get {
                return ResourceManager.GetString("CentralitaInvalidValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;Centralita&quot; es obligatorio..
        /// </summary>
        internal static string CentralitaRequiredValidation {
            get {
                return ResourceManager.GetString("CentralitaRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El formatio del CIF no es correcto..
        /// </summary>
        internal static string CifInvalidValidation {
            get {
                return ResourceManager.GetString("CifInvalidValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El CIF es obligatorio..
        /// </summary>
        internal static string CifRequiredValidation {
            get {
                return ResourceManager.GetString("CifRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;Localidad&quot; es obligatorio..
        /// </summary>
        internal static string CityRequiredValidation {
            get {
                return ResourceManager.GetString("CityRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: La situación de habilitación actual es obligatoria..
        /// </summary>
        internal static string CurrentSituationRequiredValidation {
            get {
                return ResourceManager.GetString("CurrentSituationRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: La fecha de elección del cargo es obligatoria..
        /// </summary>
        internal static string ElectedDateRequiredValidation {
            get {
                return ResourceManager.GetString("ElectedDateRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;Email&quot; no es válido..
        /// </summary>
        internal static string EmailInvalidValidation {
            get {
                return ResourceManager.GetString("EmailInvalidValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;Email&quot; es obligatorio..
        /// </summary>
        internal static string EmailRequiredValidation {
            get {
                return ResourceManager.GetString("EmailRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;Fax&quot; no es valido..
        /// </summary>
        internal static string FaxInvalidValidation {
            get {
                return ResourceManager.GetString("FaxInvalidValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;Fax&quot; es obligatorio..
        /// </summary>
        internal static string FaxRequiredValidation {
            get {
                return ResourceManager.GetString("FaxRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;Dirección Completa&quot; es obligatorio..
        /// </summary>
        internal static string FullAddressRequiredValidation {
            get {
                return ResourceManager.GetString("FullAddressRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: La fecha de concesión de la distinción es obligatoria..
        /// </summary>
        internal static string HonourDateRequiredValidation {
            get {
                return ResourceManager.GetString("HonourDateRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: La descripción de la distinción es obligatoria si el tipo de distinción es &quot;Otra&quot;..
        /// </summary>
        internal static string HonourLiteralRequiredValidation {
            get {
                return ResourceManager.GetString("HonourLiteralRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El tipo de distinción es obligatorio..
        /// </summary>
        internal static string HonourTypeRequiredValidation {
            get {
                return ResourceManager.GetString("HonourTypeRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: Es obligatorio rellenar al menos uno de los siguientes campos:  fecha de expedición de licenciatura, fecha de expedición de grado, u otros estudios..
        /// </summary>
        internal static string LawDegreeOrEquivalentRequiredValidation {
            get {
                return ResourceManager.GetString("LawDegreeOrEquivalentRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El apartado de correos no es valido. El formato correcto es un valor numérico de 2 a 5 posiciones..
        /// </summary>
        internal static string MailBoxInvalidValidation {
            get {
                return ResourceManager.GetString("MailBoxInvalidValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: La fecha de expedición del máster es obligatoria si se rellena la fecha de expedición del grado..
        /// </summary>
        internal static string MasterDegreeDateRequiredValidation {
            get {
                return ResourceManager.GetString("MasterDegreeDateRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;Movil&quot; no es valido..
        /// </summary>
        internal static string MobileInvalidValidation {
            get {
                return ResourceManager.GetString("MobileInvalidValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;Movil&quot; es obligatorio..
        /// </summary>
        internal static string MobileRequiredValidation {
            get {
                return ResourceManager.GetString("MobileRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;Nombre&quot; no es válido. Debe incluir una palabra de 1 carácter al menos..
        /// </summary>
        internal static string NameInvalidValidation {
            get {
                return ResourceManager.GetString("NameInvalidValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;Nombre&quot; es obligatorio..
        /// </summary>
        internal static string NameRequiredValidation {
            get {
                return ResourceManager.GetString("NameRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El nombre es demasiado largo. Su longitud no deber superar los {0} caracteres..
        /// </summary>
        internal static string NameTooLongValidation {
            get {
                return ResourceManager.GetString("NameTooLongValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El número de documento (NIF) no es valido..
        /// </summary>
        internal static string NifInvalidValidation {
            get {
                return ResourceManager.GetString("NifInvalidValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El número de documento (NIF) es obligatorio..
        /// </summary>
        internal static string NifRequiredValidation {
            get {
                return ResourceManager.GetString("NifRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El número  de colegiado no es valido. El formato consta de 6 dígitos..
        /// </summary>
        internal static string NumberOfAssociatedInvalidValidation {
            get {
                return ResourceManager.GetString("NumberOfAssociatedInvalidValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El número  de colegiado es obligatorio..
        /// </summary>
        internal static string NumberOfAssociatedRequiredValidation {
            get {
                return ResourceManager.GetString("NumberOfAssociatedRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El organismo del cargo es obligatorio..
        /// </summary>
        internal static string OrganizationRequiredValidation {
            get {
                return ResourceManager.GetString("OrganizationRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El órgano del cargo es obligatorio..
        /// </summary>
        internal static string OrganRequiredValidation {
            get {
                return ResourceManager.GetString("OrganRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;Teléfono&quot; no es valido..
        /// </summary>
        internal static string PhoneInvalidValidation {
            get {
                return ResourceManager.GetString("PhoneInvalidValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;Teléfono&quot; es obligatorio..
        /// </summary>
        internal static string PhoneRequiredValidation {
            get {
                return ResourceManager.GetString("PhoneRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: La fecha de expedición del título de procurador es obligatoria..
        /// </summary>
        internal static string ProcuratorDegreeDateRequiredValidation {
            get {
                return ResourceManager.GetString("ProcuratorDegreeDateRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;Provincia&quot; es obligatorio..
        /// </summary>
        internal static string ProvinceRequiredValidation {
            get {
                return ResourceManager.GetString("ProvinceRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El usuario debe tener asignado al menos un rol..
        /// </summary>
        internal static string RoleAtLeastOneRequiredValidation {
            get {
                return ResourceManager.GetString("RoleAtLeastOneRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;Rol&quot; es obligatorio..
        /// </summary>
        internal static string RoleRequiredValidation {
            get {
                return ResourceManager.GetString("RoleRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: Los roles Consejo y Colegio son incompatibles entre sí..
        /// </summary>
        internal static string RolesAssociationAndCpgeIncompatibleValidation {
            get {
                return ResourceManager.GetString("RolesAssociationAndCpgeIncompatibleValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;Apellido 1&quot; no es válido. Debe incluir una palabra de 1 carácter al menos..
        /// </summary>
        internal static string SecondName1InvalidValidation {
            get {
                return ResourceManager.GetString("SecondName1InvalidValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;Apellido 1&quot; es obligatorio..
        /// </summary>
        internal static string SecondName1RequiredValidation {
            get {
                return ResourceManager.GetString("SecondName1RequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El primer apellido es demasiado largo. Su longitud no deber superar los {0} caracteres..
        /// </summary>
        internal static string SecondName1TooLongValidation {
            get {
                return ResourceManager.GetString("SecondName1TooLongValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;Apellido 2&quot; no es válido. Debe incluir una palabra de 1 carácter al menos..
        /// </summary>
        internal static string SecondName2InvalidValidation {
            get {
                return ResourceManager.GetString("SecondName2InvalidValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El segundo apellido es demasiado largo. Su longitud no deber superar los {0} caracteres..
        /// </summary>
        internal static string SecondName2TooLongValidation {
            get {
                return ResourceManager.GetString("SecondName2TooLongValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: Fecha de estado es obligatoria..
        /// </summary>
        internal static string StateDateRequiredValidation {
            get {
                return ResourceManager.GetString("StateDateRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El número único de colegiado no es valido. El formato debe ser P12345678901..
        /// </summary>
        internal static string UniqueNumberOfAssociatedInvalidValidation {
            get {
                return ResourceManager.GetString("UniqueNumberOfAssociatedInvalidValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El número único de colegiado es obligatorio..
        /// </summary>
        internal static string UniqueNumberOfAssociatedRequiredValidation {
            get {
                return ResourceManager.GetString("UniqueNumberOfAssociatedRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;URL&quot; no es valido..
        /// </summary>
        internal static string WebInvalidValidation {
            get {
                return ResourceManager.GetString("WebInvalidValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;URL&quot; es obligatorio..
        /// </summary>
        internal static string WebRequiredValidation {
            get {
                return ResourceManager.GetString("WebRequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El código postal no es valido. El formato correcto es un valor numérico de 4 a 5 posiciones..
        /// </summary>
        internal static string ZipCodeInvalidValidation {
            get {
                return ResourceManager.GetString("ZipCodeInvalidValidation", resourceCulture);
            }
        }
    }
}
