//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgpe.Du.CrossCuttings.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cgpe.Du.CrossCuttings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurator Mandatory Fields are null or empty..
        /// </summary>
        internal static string ProcuratorMandatoryFields {
            get {
                return ResourceManager.GetString("ProcuratorMandatoryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: No dispone de los permisos necesarios para acceder a métodos destinados al BOE..
        /// </summary>
        internal static string UnathorizedAccessBOE {
            get {
                return ResourceManager.GetString("UnathorizedAccessBOE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: No dispone de los permisos necesarios para acceder a métodos destinados a integración interna del CGPE..
        /// </summary>
        internal static string UnathorizedAccessCgpeInternal {
            get {
                return ResourceManager.GetString("UnathorizedAccessCgpeInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: No dispone de los permisos necesarios para acceder a métodos destinados al CGPJ..
        /// </summary>
        internal static string UnathorizedAccessCGPJ {
            get {
                return ResourceManager.GetString("UnathorizedAccessCGPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: No dispone de los permisos necesarios para acceder a métodos destinados al Notariado..
        /// </summary>
        internal static string UnathorizedAccessNotary {
            get {
                return ResourceManager.GetString("UnathorizedAccessNotary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: No dispone de los permisos necesarios para crear un usuario..
        /// </summary>
        internal static string UnauthorizedAccessCreateUser {
            get {
                return ResourceManager.GetString("UnauthorizedAccessCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: No dispone de los permisos necesarios para consultar una lista de usuarios..
        /// </summary>
        internal static string UnauthorizedAccessQueryUsers {
            get {
                return ResourceManager.GetString("UnauthorizedAccessQueryUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: No dispone de los permisos necesarios para acceder a métodos destinados a Registradores..
        /// </summary>
        internal static string UnauthorizedAccessRegistrator {
            get {
                return ResourceManager.GetString("UnauthorizedAccessRegistrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: No dispone de los permisos necesarios para actualizar los datos de un usuario..
        /// </summary>
        internal static string UnauthorizedAccessUpdateUser {
            get {
                return ResourceManager.GetString("UnauthorizedAccessUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: No dispone de los permisos necesarios para acceder a la operación solicitada..
        /// </summary>
        internal static string UnauthorizedGeneric {
            get {
                return ResourceManager.GetString("UnauthorizedGeneric", resourceCulture);
            }
        }
    }
}
