//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgpe.Du.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cgpe.Du.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: Association Mandatory Fields are null or empty.
        /// </summary>
        public static string AssociationMandatoryFields {
            get {
                return ResourceManager.GetString("AssociationMandatoryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: Association not found.
        /// </summary>
        public static string AssociationNotFound {
            get {
                return ResourceManager.GetString("AssociationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE Signed Data String is empty.
        /// </summary>
        public static string AssociationSignedDataEmpty {
            get {
                return ResourceManager.GetString("AssociationSignedDataEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: Operación de auditoria con el Id &quot;{0}&quot; no soportada.
        /// </summary>
        public static string AuditOperationNotSupported {
            get {
                return ResourceManager.GetString("AuditOperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: No se ha podido autenticar al usuario.
        /// </summary>
        public static string AuthenticationException {
            get {
                return ResourceManager.GetString("AuthenticationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El campo &quot;{0}&quot; es obligatorio.
        /// </summary>
        public static string MandatoryFields {
            get {
                return ResourceManager.GetString("MandatoryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: Procurator Mandatory Fields are null or empty.
        /// </summary>
        public static string ProcuratorMandatoryFields {
            get {
                return ResourceManager.GetString("ProcuratorMandatoryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: Procurator not found.
        /// </summary>
        public static string ProcuratorNotFound {
            get {
                return ResourceManager.GetString("ProcuratorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: Signed Data String is empty .
        /// </summary>
        public static string ProcuratorSignedDataEmpty {
            get {
                return ResourceManager.GetString("ProcuratorSignedDataEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: Source Type &quot;{0}&quot; and Destination Type &quot;{1}&quot; are not supported.
        /// </summary>
        public static string TypeIsNotSupported {
            get {
                return ResourceManager.GetString("TypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: No dispone de los permisos necesarios para consultar los procuradores adheridos al convenio con el BOE..
        /// </summary>
        public static string UnathorizedAccessBOE {
            get {
                return ResourceManager.GetString("UnathorizedAccessBOE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: No dispone de permisos necesarios para crear un Procurador.
        /// </summary>
        public static string UnauthorizedAccessCreateProcurators {
            get {
                return ResourceManager.GetString("UnauthorizedAccessCreateProcurators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: No dispone de permisos necesarios para crear un Usuario.
        /// </summary>
        public static string UnauthorizedAccessCreateUser {
            get {
                return ResourceManager.GetString("UnauthorizedAccessCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: No dispone de permisos necesarios para consultar una Lista de Colegios.
        /// </summary>
        public static string UnauthorizedAccessGetAssociations {
            get {
                return ResourceManager.GetString("UnauthorizedAccessGetAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: No dispone de permisos necesarios para consultar una Lista de Procuradores.
        /// </summary>
        public static string UnauthorizedAccessGetProcurators {
            get {
                return ResourceManager.GetString("UnauthorizedAccessGetProcurators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: No dispone de permisos necesarios para consultar una Lista de usuarios.
        /// </summary>
        public static string UnauthorizedAccessGetUsers {
            get {
                return ResourceManager.GetString("UnauthorizedAccessGetUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: No dispone de permisos necesarios para actualizar los datos de un Colegio.
        /// </summary>
        public static string UnauthorizedAccessUpdateAssociation {
            get {
                return ResourceManager.GetString("UnauthorizedAccessUpdateAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: No dispone de permisos necesarios para actualizar los datos de un Procurador.
        /// </summary>
        public static string UnauthorizedAccessUpdateProcurators {
            get {
                return ResourceManager.GetString("UnauthorizedAccessUpdateProcurators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: No dispone de permisos necesarios para actualizar los datos de un Usuario.
        /// </summary>
        public static string UnauthorizedAccessUpdateUser {
            get {
                return ResourceManager.GetString("UnauthorizedAccessUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: El usuario con el Id &quot;{0}&quot; no existe.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: Invalid Arguments.
        /// </summary>
        public static string warning_InvalidArgumentForFindRecords {
            get {
                return ResourceManager.GetString("warning_InvalidArgumentForFindRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGPE: Id is null, empty or Guid.Empty.
        /// </summary>
        public static string warning_SearchIdIsNullEmpty {
            get {
                return ResourceManager.GetString("warning_SearchIdIsNullEmpty", resourceCulture);
            }
        }
    }
}
